name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  client-build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: mern/client
        run: npm install

      - name: Check Build
        working-directory: mern/client
        run: npm run build
        
  server-build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set Up nodejs
        uses: actions/setup-node@v3
      - name: Install Packages
        working-directory: mern/server
        run: npm install
